name: Remote build using SSH
on: [ push ]
env:
  PROJECT: ${{ github.event.repository.name }}
  DIR: /home/${{ secrets.USERNAME }}/${{ github.event.repository.name }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Run remote build
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            ln -sf ${{ env.DIR }}/.env ${{ env.DIR }}/build/.env 
            cd ${{ env.DIR }}/build
            git pull
            /usr/local/go/bin/go mod tidy
            /usr/local/go/bin/go generate ./...
            /usr/local/go/bin/go build
            /usr/local/go/bin/go run migrate/migrate.go
            sudo systemctl restart ${{ env.PROJECT }}
