name: Remote Build using SSH
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Run remote build
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            host -V
            ls -la
