name: Remote prepare project dir
on:
  workflow_dispatch: # Trigger workflow manually
env:
  PROJECT: ${{ github.event.repository.name }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Run remote build
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            mkdir -p /home/${{ secrets.USERNAME }}/${{ env.PROJECT }}
            mkdir -p /home/${{ secrets.USERNAME }}/${{ env.PROJECT }}/build
            touch /home/${{ secrets.USERNAME }}/${{ env.PROJECT }}/.env
            cd /home/${{ secrets.USERNAME }}/${{ env.PROJECT }}/build
            git clone https://github.com/7binary//${{ env.PROJECT }}.git .
